// Code generated by baton-sdk. DO NOT EDIT!!!
package config

import "reflect" 

type OktaAwsFederation struct {
	Domain string `mapstructure:"domain"`
	ApiToken string `mapstructure:"api-token"`
	Cache bool `mapstructure:"cache"`
	CacheTti int `mapstructure:"cache-tti"`
	CacheTtl int `mapstructure:"cache-ttl"`
	SkipSecondaryEmails bool `mapstructure:"skip-secondary-emails"`
	AwsOktaAppId string `mapstructure:"aws-okta-app-id"`
	AwsSourceIdentityMode bool `mapstructure:"aws-source-identity-mode"`
	AwsAllowGroupToDirectAssignmentConversionForProvisioning bool `mapstructure:"aws-allow-group-to-direct-assignment-conversion-for-provisioning"`
}

func (c* OktaAwsFederation) findFieldByTag(tagValue string) (any, bool) {
	v := reflect.ValueOf(c).Elem() // Dereference pointer to struct
	t := v.Type()

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)
		tag := field.Tag.Get("mapstructure")

		if tag == tagValue {
			return v.Field(i).Interface(), true
		}
	}
	return nil, false
}

func (c *OktaAwsFederation) GetStringSlice(fieldName string) []string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return []string{}
	}
	t, ok := v.([]string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *OktaAwsFederation) GetString(fieldName string) string {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return ""
	}
	t, ok := v.(string)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *OktaAwsFederation) GetInt(fieldName string) int {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return 0
	}
	t, ok := v.(int)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *OktaAwsFederation) GetBool(fieldName string) bool {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return false
	}
	t, ok := v.(bool)
	if !ok {
		panic("wrong type")
	}
	return t
}

func (c *OktaAwsFederation) GetStringMap(fieldName string) map[string]any {
	v, ok := c.findFieldByTag(fieldName)
	if !ok {
		return map[string]any{}
	}
	t, ok := v.(map[string]any)
	if !ok {
		panic("wrong type")
	}
	return t
}
