name: ci
on: pull_request
jobs:
  test:
    runs-on: ubuntu-latest
    env:
      BATON_LOG_LEVEL: debug
      # Add any environment variables needed to run baton-okta-aws-federation
      BATON_API_TOKEN: ${{ secrets.BATON_API_TOKEN }}
      BATON_DOMAIN: ${{ secrets.BATON_DOMAIN }}
      BATON_AWS_OKTA_APP_ID: ${{ secrets.BATON_AWS_OKTA_APP_ID }}
      # The following parameters are passed to grant/revoke commands
      CONNECTOR_GRANT: ${{ vars.CONNECTOR_GRANT }}
      CONNECTOR_ENTITLEMENT: ${{ vars.CONNECTOR_ENTITLEMENT }}
      CONNECTOR_PRINCIPAL_TYPE: ${{ vars.CONNECTOR_PRINCIPAL_TYPE }}
      CONNECTOR_PRINCIPAL: ${{ vars.CONNECTOR_PRINCIPAL }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
      - name: Install baton
        uses: conductorone/github-workflows/actions/get-baton@v4
      - name: Build baton-okta-aws-federation
        run: go build ./cmd/baton-okta-aws-federation
      - name: Run baton-okta-aws-federation
        run: ./baton-okta-aws-federation
      # - name: Grant entitlement (even though it probably already exists)
      #   run: |
      #     ./baton-okta-aws-federation --grant-entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --grant-principal ${{ env.CONNECTOR_PRINCIPAL }} --grant-principal-type ${{ env.CONNECTOR_PRINCIPAL_TYPE }}
      - name: Check for grant
        run: |
          ./baton-okta-aws-federation && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource ==\"${{ env.CONNECTOR_PRINCIPAL }}\")"
        # - name: Revoke grants
        #   run: |
        #     ./baton-okta-aws-federation --revoke-grant ${{ env.CONNECTOR_GRANT }}
        # - name: Check grant was revoked
        #   run: |
        #      ./baton-okta-aws-federation && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource !=\"${{ env.CONNECTOR_PRINCIPAL }}\")"
        # - name: Grant entitlement
        #   run: | 
        #     ./baton-okta-aws-federation && ./baton-okta-aws-federation --grant-entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --grant-principal ${{ env.CONNECTOR_PRINCIPAL }} --grant-principal-type ${{ env.CONNECTOR_PRINCIPAL_TYPE }}
        # - name: Check grant was re-granted
        #   run: |
        #     ./baton-okta-aws-federation && baton grants --entitlement ${{ env.CONNECTOR_ENTITLEMENT }} --output-format=json | jq -e ".grants | any(.principal.id.resource ==\"${{ env.CONNECTOR_PRINCIPAL }}\")"
